services:
  nmea-gps:
    image: husarion/nmea-gps:humble-2.0.1-20240617
    network_mode: host
    restart: always
    command: >
      ros2 launch /husarion_utils/nmea_navsat.launch.py
        robot_namespace:=panther
